name: Deploy develop

on:
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: darwinia-network/devops
          path: .github

      - uses: ./.github/actions/smart-vercel
        name: Deploy to Vercel
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          project_name: staking-ui
          dist_path: .
          script_run: false
          enable_notify_comment: true
          enable_notify_slack: true
          slack_channel: public-ringdao-apps
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
